/* eslint-disable */
// Keep this generated Worker environment module-scoped in the multi-Worker repository.
export type { StagingKaraokeResetCallerEnv };

// Generated by Wrangler by running `wrangler types --config=apps/staging-karaoke-reset-caller/wrangler.jsonc --env=staging --include-runtime=false --env-interface=StagingKaraokeResetCallerEnv apps/staging-karaoke-reset-caller/worker-configuration.d.ts` (hash: 7d6d000da1f4968b2bd8ec56bdddc139)
interface __BaseEnv_StagingKaraokeResetCallerEnv {
  API_NEXT_ENV: "staging";
  KARAOKE_RESET_ENABLED: "false";
  RESET_OPERATOR: Service /* entrypoint KaraokeResetOperatorEntrypoint from pirate-http-worker-staging */;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
  }
  interface Env extends __BaseEnv_StagingKaraokeResetCallerEnv {}
}
interface StagingKaraokeResetCallerEnv extends __BaseEnv_StagingKaraokeResetCallerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "API_NEXT_ENV" | "KARAOKE_RESET_ENABLED">> {}
}
