/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --env-file=.env.example --include-runtime=false` (hash: ac0d990ed4ad06352b7f422cc4c25b2c)
interface __BaseEnv_Env {
  PROOF_BUCKET: R2Bucket;
  PROOF_PREFIX: "local-r2-binding-proof";
  PROOF_TARGET_LABEL: "local-only";
  PROOF_RUN_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "PROOF_PREFIX" | "PROOF_TARGET_LABEL" | "PROOF_RUN_TOKEN">
    > {}
}
