import { describe, expect, test } from "bun:test";
import { canonicalTextModerationInput, normalizeTextModerationInput } from "@pirate/domain";
import { Cause, Effect, Exit, Result } from "effect";
import { TextModerationProviderError, type TextPostModerationEvaluation, TextPostRepositoryError, type TextPostPreparation, type TextPostStore } from "../../ports.ts";
import { createTextPost, getTextContentSubmission } from "./text-post.ts";
const actor = { userId: "usr_alice", kind: "user" as const };
const hash = "a".repeat(64);
const body = { post_type: "text" as const, idempotency_key: "key_1", body: "hello" };
const published = { submission_id: "submission_1", href: "/text-content-submissions/submission_1", surface: "text_post" as const, status: "published" as const, result: { decision: "allow" as const, reason_code: null }, published_resource: { kind: "post" as const, post_id: "post_1", href: "/posts/post_1" }, review_ref: null, created_at: "2026-08-21T12:00:00.000Z", updated_at: "2026-08-21T12:00:00.000Z" };
const inputHash = () => { const n = normalizeTextModerationInput({ surface: "text_post", body: "hello" }); if (n.kind === "rejected") throw new Error(n.reason); const c = canonicalTextModerationInput(n.input); if (c.kind === "rejected") throw new Error(c.reason); return c.sha256; };
const preparation = (revision = "text-policy-1"): TextPostPreparation => ({ operationId: "operation_1", submissionId: "submission_1", communityId: "community_1", actorId: actor.userId, idempotencyKey: body.idempotency_key, requestHash: "b".repeat(64), inputSha256: inputHash(), policyRevision: revision, policyHash: hash });
const evaluation = (revision = "text-policy-1", decision: "allow" | "manual_review" = "allow"): TextPostModerationEvaluation => ({ version: "text-moderation-v1", surface: "text_post", decision, reason_codes: decision === "allow" ? [] : ["provider_timeout"], policy_revision: revision, policy_hash: hash, input_sha256: inputHash(), evidence_ref: null });
const store = (overrides: Partial<TextPostStore["Service"]> = {}): TextPostStore["Service"] => ({ replay: () => Effect.succeed({ kind: "none" as const }), prepare: () => Effect.succeed({ kind: "prepared" as const, preparation: preparation() }), commit: () => Effect.succeed({ kind: "created" as const, snapshot: published }), getForAuthor: () => Effect.succeed(published), ...overrides });
const run = <A, E>(effect: Effect.Effect<A, E>) => Effect.runPromiseExit(effect);

describe("moderated text post application", () => {
  test("replays before moderation", async () => { let calls = 0; const result = await run(createTextPost({ communityId: "community_1", actor, body }, { store: store({ replay: () => Effect.succeed({ kind: "replay", snapshot: published }) }), moderation: { evaluate: () => { calls += 1; return Effect.succeed(evaluation()); } } })); expect(Exit.isSuccess(result) ? result.value : undefined).toEqual(published); expect(calls).toBe(0); });
  test("moderates outside commit and retries stale policy", async () => { let count = 0; const result = await run(createTextPost({ communityId: "community_1", actor, body }, { store: store({ prepare: () => { count += 1; return Effect.succeed({ kind: "prepared" as const, preparation: preparation(count === 1 ? "text-policy-1" : "text-policy-2") }); }, commit: () => Effect.succeed(count === 1 ? ({ kind: "policy-stale", policyRevision: "text-policy-2", policyHash: hash } as const) : ({ kind: "created", snapshot: published } as const)) }), moderation: { evaluate: () => Effect.succeed(evaluation(count === 1 ? "text-policy-1" : "text-policy-2")) } })); expect(Exit.isSuccess(result) ? result.value : undefined).toEqual(published); expect(count).toBe(2); });
  test("maps same-key hash conflict", async () => { const result = await run(createTextPost({ communityId: "community_1", actor, body }, { store: store({ replay: () => Effect.succeed({ kind: "conflict", submissionId: "submission_9" }) }), moderation: { evaluate: () => Effect.succeed(evaluation()) } })); if (Exit.isSuccess(result)) throw new Error("expected conflict"); const failure = Cause.findError(result.cause); expect(Result.isSuccess(failure) ? failure.success : undefined).toMatchObject({ _tag: "IdempotencyConflict", details: { submission_id: "submission_9" } }); });
  test("holds provider failure", async () => { let committed: TextPostModerationEvaluation | undefined; const result = await run(createTextPost({ communityId: "community_1", actor, body }, { store: store({ commit: ({ evaluation: value }) => { committed = value; return Effect.succeed({ kind: "created" as const, snapshot: published }); } }), moderation: { evaluate: () => Effect.fail(new TextModerationProviderError({ reason: "timeout" })) } })); expect(Exit.isSuccess(result)).toBe(true); expect(committed).toMatchObject({ decision: "manual_review", reason_codes: ["provider_timeout"] }); });
  test("GET returns current author state without moderation", async () => { const result = await run(getTextContentSubmission({ submissionId: "submission_1", actor }, { store: store() })); expect(Exit.isSuccess(result) ? result.value : undefined).toEqual(published); });
  test("maps invalid repository rows", async () => { const result = await run(getTextContentSubmission({ submissionId: "submission_1", actor }, { store: store({ getForAuthor: () => Effect.fail(new TextPostRepositoryError({ operation: "get", reason: "invalid-row" })) }) })); expect(Exit.isFailure(result)).toBe(true); });
});
