export const reusablePostgresTestSuites = [
  "packages/platform-cf/src/telegram-store.pg.test.ts",
  "packages/platform-cf/src/activity-qualification-repository.pg.test.ts",
  "packages/platform-cf/src/community-creation-repository.pg.test.ts",
  "packages/platform-cf/src/community-owner-reservation.pg.test.ts",
  "packages/platform-cf/src/community-purchase-funding-producer-repository.pg.test.ts",
  "packages/platform-cf/src/community-repository.pg.test.ts",
  "packages/platform-cf/src/community-route-repository.pg.test.ts",
  "packages/platform-cf/src/dance-reference-persistence.pg.test.ts",
  "packages/platform-cf/src/feed-repository.pg.test.ts",
  "packages/platform-cf/src/hns-control-observer-repository.pg.test.ts",
  "packages/platform-cf/src/hns-route-revalidation-scheduler.pg.test.ts",
  "packages/platform-cf/src/identity.pg.test.ts",
  "packages/platform-cf/src/media-persistence.pg.test.ts",
  "packages/platform-cf/src/namespace-ownership-persistence.pg.test.ts",
  "packages/platform-cf/src/platform-pirate-handle-repository.pg.test.ts",
  "packages/platform-cf/src/public-post-slug-repository.pg.test.ts",
  "packages/platform-cf/src/public-profile.pg.test.ts",
  "packages/platform-cf/src/rewards-qualification.pg.test.ts",
  "packages/platform-cf/src/rewards-song-offers.pg.test.ts",
  "packages/platform-cf/src/song-owner-video-policy.pg.test.ts",
  "packages/platform-cf/src/route-revalidation-completion-repository.pg.test.ts",
  "packages/platform-cf/src/video-publication-repository.pg.test.ts",
  "packages/platform-cf/src/video-reservation-cleanup.pg.test.ts",
  "packages/platform-cf/src/video-stream-ingest-repository.pg.test.ts",
  "packages/platform-cf/src/video-thumbnail-repository.pg.test.ts",
  "scripts/community-purchase-funding-plans.pg.test.ts",
  "scripts/very-staging-community-fixture.pg.test.ts",
] as const;

export const freshSchemaPostgresTestSuites = [
  "apps/http-worker/src/hns-community-publication.pg.test.ts",
  "apps/http-worker/src/public-community-threads-composition.pg.test.ts",
  "scripts/hns-monitor/snapshot.pg.test.ts",
  "scripts/hns-continuity/promotion.pg.test.ts",
  "packages/platform-cf/src/community-purchase-funding-repository.pg.test.ts",
  "packages/platform-cf/src/content-repository.pg.test.ts",
  "packages/platform-cf/src/dance-attempt-persistence.pg.test.ts",
  "packages/platform-cf/src/data-registration-repository.pg.test.ts",
  "packages/platform-cf/src/gates-v2-community.pg.test.ts",
  "packages/platform-cf/src/handle-sales-repository.pg.test.ts",
  "packages/platform-cf/src/hns-host-persistence-repository.pg.test.ts",
  "packages/platform-cf/src/hns-community-root-import-repository.pg.test.ts",
  "packages/platform-cf/src/hns-root-import-repository.pg.test.ts",
  "packages/platform-cf/src/hns-root-import-lifecycle.pg.test.ts",
  "packages/platform-cf/src/hns-root-import-lifecycle-migration.pg.test.ts",
  "packages/platform-cf/src/hns-root-import-lifecycle-privileges.pg.test.ts",
  // Both create their own schema and run every migration, so they classify
  // with the fresh-schema suites rather than the baseline-reusing ones.
  "packages/platform-cf/src/hns-root-import-lifecycle-transition.pg.test.ts",
  "packages/platform-cf/src/hns-root-import-lifecycle-execution.pg.test.ts",
  "packages/platform-cf/src/hns-lifecycle-readiness-patch.pg.test.ts",
  "packages/platform-cf/src/hns-retention-review.pg.test.ts",
  "packages/platform-cf/src/hns-execution-ownership.pg.test.ts",
  "packages/platform-cf/src/hns-retention-reviewer.pg.test.ts",
  "packages/platform-cf/src/hns-lifecycle-projection.pg.test.ts",
  "packages/platform-cf/src/hns-observation-fence.pg.test.ts",
  "packages/platform-cf/src/hns-incident-recovery.pg.test.ts",
  // Creates its own schema and additionally needs a reachable regtest node;
  // it skips itself when either is absent.
  "packages/platform-cf/src/hns-lifecycle-composed-path.pg.test.ts",
  "packages/platform-cf/src/hns-incident-evidence.pg.test.ts",
  // Drives the provisioner's own entrypoint as a subprocess against a fresh
  // database and a regtest node; it skips itself when either is absent.
  "packages/platform-cf/src/hns-service-loop-entrypoint.pg.test.ts",
  "packages/platform-cf/src/karaoke-finalization-recovery.pg.test.ts",
  "packages/platform-cf/src/learner-audio-deletion-repository.pg.test.ts",
  "packages/platform-cf/src/localization-foundation.pg.test.ts",
  "packages/platform-cf/src/optional-route-v2-migration.pg.test.ts",
  "packages/platform-cf/src/persona-repository.pg.test.ts",
  "packages/platform-cf/src/public-community-threads-repository.pg.test.ts",
  "packages/platform-cf/src/study-v2-foundation.pg.test.ts",
  "packages/platform-cf/src/study-translation-repository.pg.test.ts",
  "packages/platform-cf/src/verification-completion-repository.pg.test.ts",
  "packages/platform-cf/src/verification-start-repository.pg.test.ts",
  "scripts/public-post-slug-backfill.pg.test.ts",
  "scripts/public-profile-backfill.pg.test.ts",
] as const;

export const noBaselinePostgresTestSuites = [
  "scripts/staging-karaoke-release-database.pg.test.ts",
  "scripts/staging-persona-reset-denied-grants.pg.test.ts",
  "scripts/staging-persona-recovery.pg.test.ts",
  "scripts/staging-persona-dependency-scan.pg.test.ts",
  "scripts/staging-persona-schema-authority.pg.test.ts",
  "scripts/staging-persona-session-drain.pg.test.ts",
  "scripts/staging-persona-runtime-denial.pg.test.ts",
  "scripts/staging-persona-database-collector.pg.test.ts",
  "scripts/staging-karaoke-nonreuse.pg.test.ts",
  "scripts/staging-persona-reset-replay.pg.test.ts",
  "scripts/staging-persona-reconstruct.pg.test.ts",
  "scripts/staging-persona-phased-reset.pg.test.ts",
  "packages/platform-cf/src/hns-renewal-privileges.pg.test.ts",
  "packages/platform-cf/src/hns-admission-privileges.pg.test.ts",
  "packages/platform-cf/src/video-reconciliation-operator.pg.test.ts",
  "packages/platform-cf/src/video-source-grants.pg.test.ts",
  "packages/platform-cf/src/video-safety-evidence.pg.test.ts",
  "packages/platform-cf/src/video-workflow-composed.pg.test.ts",
  "packages/platform-cf/src/video-transform-attempt-repository.pg.test.ts",
  "packages/platform-cf/src/video-workflow-migration.pg.test.ts",
  "packages/platform-cf/src/video-publication-reasons-migration.pg.test.ts",
  "packages/platform-cf/src/community-moderation-foundation.pg.test.ts",
  "packages/platform-cf/src/community-membership-follow-invariant.pg.test.ts",
  "packages/platform-cf/src/community-route-migration.pg.test.ts",
  "packages/platform-cf/src/media-persistence-migrations.pg.test.ts",
  "packages/platform-cf/src/persona-community-binding-migration.pg.test.ts",
  "packages/platform-cf/src/karaoke-persona-boundary.pg.test.ts",
  "packages/platform-cf/src/postgres-foundation.pg.test.ts",
  "packages/platform-cf/src/postgres-migrations-runner.pg.test.ts",
  "packages/platform-cf/src/postgres.pg.test.ts",
  "packages/platform-cf/src/text-submission-repository.pg.test.ts",
] as const;

export const classifiedPostgresTestSuites = [
  ...reusablePostgresTestSuites,
  ...freshSchemaPostgresTestSuites,
  ...noBaselinePostgresTestSuites,
] as const;
