import { generateKeyPairSync } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Local harness key material. Never a real credential: the pair is generated on
 * this machine, written only to the gitignored `.local/` directory, and used
 * exclusively to mint synthetic browser sessions for the disposable database.
 */
export interface HarnessKeys {
  readonly privateKeyPem: string;
  readonly publicKeyPem: string;
  readonly csrfToken: string;
}

const harnessDirectory = dirname(fileURLToPath(import.meta.url));
const localDirectory = join(harnessDirectory, ".local");
const keysPath = join(localDirectory, "keys.json");

interface StoredKeys {
  readonly privateKeyPem: string;
  readonly publicKeyPem: string;
  readonly csrfToken: string;
}

function generated(): StoredKeys {
  const pair = generateKeyPairSync("rsa", {
    modulusLength: 2_048,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });
  const csrfBytes = new Uint8Array(24);
  crypto.getRandomValues(csrfBytes);
  return {
    privateKeyPem: pair.privateKey.trim(),
    publicKeyPem: pair.publicKey.trim(),
    csrfToken: Buffer.from(csrfBytes).toString("base64url"),
  };
}

function readStored(): StoredKeys | null {
  if (!existsSync(keysPath)) return null;
  const parsed: unknown = JSON.parse(readFileSync(keysPath, "utf8"));
  if (typeof parsed !== "object" || parsed === null) {
    throw new Error("Harness key file is malformed; remove .local/keys.json to regenerate");
  }
  const candidate = parsed as Record<string, unknown>;
  const privateKeyPem = candidate.privateKeyPem;
  const publicKeyPem = candidate.publicKeyPem;
  const csrfToken = candidate.csrfToken;
  if (
    typeof privateKeyPem !== "string" ||
    typeof publicKeyPem !== "string" ||
    typeof csrfToken !== "string"
  ) {
    throw new Error("Harness key file is malformed; remove .local/keys.json to regenerate");
  }
  return {
    privateKeyPem: privateKeyPem.trim(),
    publicKeyPem: publicKeyPem.trim(),
    csrfToken,
  };
}

export function ensureHarnessKeys(): HarnessKeys {
  mkdirSync(localDirectory, { recursive: true });
  const stored = readStored() ?? generated();
  if (!existsSync(keysPath)) writeFileSync(keysPath, `${JSON.stringify(stored, null, 2)}\n`);
  return stored;
}

/** Writes the wrangler dev-mode variable file next to the harness config. */
export function writeDevVars(keys: HarnessKeys): string {
  const devVarsPath = join(harnessDirectory, ".dev.vars");
  const lines = [
    "# Generated by tests/study-karaoke-harness: local-only synthetic values.",
    `PIRATE_APP_JWT_PRIVATE_KEY="${keys.privateKeyPem.replaceAll("\n", "\\n")}"`,
    `PIRATE_APP_JWT_PUBLIC_KEY="${keys.publicKeyPem.replaceAll("\n", "\\n")}"`,
    'PRIVY_APP_SECRET="harness-local-not-a-secret"',
    'ELEVENLABS_API_KEY="harness-local-not-a-secret"',
    'OPENAI_API_KEY="harness-local-not-a-secret"',
    "",
  ];
  writeFileSync(devVarsPath, lines.join("\n"));
  return devVarsPath;
}

if (import.meta.main) {
  const keys = ensureHarnessKeys();
  const devVarsPath = writeDevVars(keys);
  console.log(`harness keys ready: ${keysPath}`);
  console.log(`dev vars written: ${devVarsPath}`);
}
